# Generated by Django 6.0.6 on 2026-07-29 09:24

import uuid
from itertools import batched

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import processing.models


def create_legacy_capture_metadata_states(apps, schema_editor):  # noqa: ARG001
    Photo = apps.get_model("picflow", "Photo")
    PhotoProcessingState = apps.get_model("processing", "PhotoProcessingState")
    for photo_ids in batched(Photo.objects.values_list("pk", flat=True).iterator(), 500):
        PhotoProcessingState.objects.bulk_create(
            [
                PhotoProcessingState(photo_id=photo_id, processor_type="capture_metadata")
                for photo_id in photo_ids
            ],
            ignore_conflicts=True,
            batch_size=500,
        )


def remove_processing_states(apps, schema_editor):  # noqa: ARG001
    PhotoProcessingState = apps.get_model("processing", "PhotoProcessingState")
    PhotoProcessingState.objects.filter(processor_type="capture_metadata").delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("picflow", "0005_validate_photo_private_original_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventProcessingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contract_version", models.PositiveSmallIntegerField()),
                ("processor_type", models.CharField(max_length=64)),
                ("processor_version", models.PositiveSmallIntegerField()),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                ("configuration_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("collecting", "Collecting"),
                            ("sealed", "Sealed"),
                            ("closed", "Closed"),
                        ],
                        default="collecting",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sealed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "report",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_report_json]
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_runs",
                        to="picflow.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contract_version", models.PositiveSmallIntegerField()),
                ("processor_type", models.CharField(max_length=64)),
                ("processor_version", models.PositiveSmallIntegerField()),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                ("configuration_hash", models.CharField(max_length=64)),
                (
                    "input_fingerprint",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("retry_wait", "Retry wait"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_jobs",
                        to="picflow.event",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_jobs",
                        to="picflow.photo",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="processing.eventprocessingrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contract_version", models.PositiveSmallIntegerField()),
                ("processor_type", models.CharField(max_length=64)),
                ("processor_version", models.PositiveSmallIntegerField()),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                (
                    "input_fingerprint",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                ("worker_build", models.CharField(blank=True, default="", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("stale", "Stale"),
                        ],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                ("result_hash", models.CharField(blank=True, default="", max_length=64)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_detail", models.CharField(blank=True, default="", max_length=512)),
                ("download_duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("compute_duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("total_duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("worker_started_at", models.DateTimeField(blank=True, null=True)),
                ("worker_finished_at", models.DateTimeField(blank=True, null=True)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_attempts",
                        to="picflow.event",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_attempts",
                        to="picflow.photo",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="processing.eventprocessingrun",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="processing.processingjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhotoProcessingState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("processor_type", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_requested", "Not requested"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("retry_wait", "Retry wait"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_requested",
                        max_length=16,
                    ),
                ),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("processing_at", models.DateTimeField(blank=True, null=True)),
                ("succeeded_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_states",
                        to="processing.eventprocessingrun",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_states",
                        to="picflow.photo",
                    ),
                ),
                (
                    "accepted_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accepted_states",
                        to="processing.processingattempt",
                    ),
                ),
                (
                    "current_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_states",
                        to="processing.processingattempt",
                    ),
                ),
                (
                    "current_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_states",
                        to="processing.processingjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingLateReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("received_at", models.DateTimeField()),
                (
                    "payload",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="late_receipt",
                        to="processing.processingattempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingConflictAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("received_at", models.DateTimeField()),
                ("submitted_hash", models.CharField(max_length=64)),
                ("code", models.CharField(default="terminal_conflict", max_length=64)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conflicts",
                        to="processing.processingattempt",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_conflicts",
                        to="picflow.event",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conflicts",
                        to="processing.processingjob",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="eventprocessingrun",
            index=models.Index(
                fields=["event", "status", "processor_type"], name="proc_run_event_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprocessingrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("collecting", "sealed", "closed"))),
                name="proc_run_status_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["status", "available_at"], name="proc_job_claim_idx"),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["contract_version", "processor_type", "processor_version", "status"],
                name="proc_job_contract_claim_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="processingjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("queued", "processing", "retry_wait", "succeeded", "failed", "cancelled"),
                    )
                ),
                name="proc_job_status_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="processingjob",
            constraint=models.UniqueConstraint(
                fields=(
                    "run",
                    "photo",
                    "contract_version",
                    "processor_type",
                    "processor_version",
                    "configuration_hash",
                ),
                name="proc_job_exact_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="processingattempt",
            index=models.Index(fields=["job", "status"], name="proc_attempt_job_status_idx"),
        ),
        migrations.AddIndex(
            model_name="processingattempt",
            index=models.Index(fields=["lease_expires_at"], name="proc_attempt_lease_idx"),
        ),
        migrations.AddConstraint(
            model_name="processingattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("in_progress", "succeeded", "failed", "expired", "stale"))
                ),
                name="proc_attempt_status_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="processingattempt",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("status", "in_progress"), ("terminal_at__isnull", True))
                    | models.Q(
                        ("status__in", ("succeeded", "failed", "expired", "stale")),
                        ("terminal_at__isnull", False),
                    )
                ),
                name="proc_attempt_terminal_timestamp_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="photoprocessingstate",
            index=models.Index(fields=["status", "next_attempt_at"], name="proc_state_claim_idx"),
        ),
        migrations.AddConstraint(
            model_name="photoprocessingstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "not_requested",
                            "queued",
                            "processing",
                            "retry_wait",
                            "succeeded",
                            "failed",
                            "cancelled",
                        ),
                    )
                ),
                name="proc_state_status_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="photoprocessingstate",
            constraint=models.UniqueConstraint(
                fields=("photo", "processor_type"), name="proc_state_photo_processor_uniq"
            ),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION proc_validate_job_identity() RETURNS trigger AS $$
                BEGIN
                    IF TG_OP = 'INSERT' AND NOT EXISTS (
                        SELECT 1
                        FROM processing_eventprocessingrun AS run
                        WHERE run.id = NEW.run_id
                          AND run.status = 'collecting'
                    ) THEN
                        RAISE EXCEPTION 'processing jobs can only join collecting runs'
                            USING ERRCODE = '23514';
                    END IF;
                    IF NOT EXISTS (
                        SELECT 1
                        FROM processing_eventprocessingrun AS run
                        JOIN picflow_photo AS photo ON photo.id = NEW.photo_id
                        WHERE run.id = NEW.run_id
                          AND run.event_id = NEW.event_id
                          AND photo.event_id = NEW.event_id
                          AND run.contract_version = NEW.contract_version
                          AND run.processor_type = NEW.processor_type
                          AND run.processor_version = NEW.processor_version
                          AND run.configuration = NEW.configuration
                          AND run.configuration_hash = NEW.configuration_hash
                    ) THEN
                        RAISE EXCEPTION 'processing job must match its run and photo identity'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_job_identity_trg
                BEFORE INSERT OR UPDATE ON processing_processingjob
                FOR EACH ROW EXECUTE FUNCTION proc_validate_job_identity();

                CREATE FUNCTION proc_guard_run_identity() RETURNS trigger AS $$
                BEGIN
                    IF OLD.event_id IS DISTINCT FROM NEW.event_id
                       OR OLD.contract_version IS DISTINCT FROM NEW.contract_version
                       OR OLD.processor_type IS DISTINCT FROM NEW.processor_type
                       OR OLD.processor_version IS DISTINCT FROM NEW.processor_version
                       OR OLD.configuration IS DISTINCT FROM NEW.configuration
                       OR OLD.configuration_hash IS DISTINCT FROM NEW.configuration_hash THEN
                        RAISE EXCEPTION 'processing run identity is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_run_identity_guard_trg
                BEFORE UPDATE ON processing_eventprocessingrun
                FOR EACH ROW EXECUTE FUNCTION proc_guard_run_identity();

                CREATE FUNCTION proc_guard_job_identity() RETURNS trigger AS $$
                BEGIN
                    IF OLD.event_id IS DISTINCT FROM NEW.event_id
                       OR OLD.run_id IS DISTINCT FROM NEW.run_id
                       OR OLD.photo_id IS DISTINCT FROM NEW.photo_id
                       OR OLD.contract_version IS DISTINCT FROM NEW.contract_version
                       OR OLD.processor_type IS DISTINCT FROM NEW.processor_type
                       OR OLD.processor_version IS DISTINCT FROM NEW.processor_version
                       OR OLD.configuration IS DISTINCT FROM NEW.configuration
                       OR OLD.configuration_hash IS DISTINCT FROM NEW.configuration_hash
                       OR OLD.input_fingerprint IS DISTINCT FROM NEW.input_fingerprint THEN
                        RAISE EXCEPTION 'processing job identity is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_job_identity_guard_trg
                BEFORE UPDATE ON processing_processingjob
                FOR EACH ROW EXECUTE FUNCTION proc_guard_job_identity();

                CREATE FUNCTION proc_validate_attempt_identity() RETURNS trigger AS $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM processing_processingjob AS job
                        WHERE job.id = NEW.job_id
                          AND job.event_id = NEW.event_id
                          AND job.run_id = NEW.run_id
                          AND job.photo_id = NEW.photo_id
                          AND job.contract_version = NEW.contract_version
                          AND job.processor_type = NEW.processor_type
                          AND job.processor_version = NEW.processor_version
                          AND job.configuration = NEW.configuration
                          AND job.input_fingerprint = NEW.input_fingerprint
                    ) THEN
                        RAISE EXCEPTION 'processing attempt must match its job identity'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_attempt_identity_trg
                BEFORE INSERT OR UPDATE ON processing_processingattempt
                FOR EACH ROW EXECUTE FUNCTION proc_validate_attempt_identity();

                CREATE FUNCTION proc_guard_attempt_identity() RETURNS trigger AS $$
                BEGIN
                    IF OLD.event_id IS DISTINCT FROM NEW.event_id
                       OR OLD.run_id IS DISTINCT FROM NEW.run_id
                       OR OLD.job_id IS DISTINCT FROM NEW.job_id
                       OR OLD.photo_id IS DISTINCT FROM NEW.photo_id
                       OR OLD.contract_version IS DISTINCT FROM NEW.contract_version
                       OR OLD.processor_type IS DISTINCT FROM NEW.processor_type
                       OR OLD.processor_version IS DISTINCT FROM NEW.processor_version
                       OR OLD.configuration IS DISTINCT FROM NEW.configuration
                       OR OLD.input_fingerprint IS DISTINCT FROM NEW.input_fingerprint THEN
                        RAISE EXCEPTION 'processing attempt identity is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_attempt_identity_guard_trg
                BEFORE UPDATE ON processing_processingattempt
                FOR EACH ROW EXECUTE FUNCTION proc_guard_attempt_identity();

                CREATE FUNCTION proc_validate_state_identity() RETURNS trigger AS $$
                BEGIN
                    IF NEW.current_run_id IS NOT NULL AND NOT EXISTS (
                        SELECT 1
                        FROM processing_eventprocessingrun AS run
                        JOIN picflow_photo AS photo ON photo.id = NEW.photo_id
                        WHERE run.id = NEW.current_run_id
                          AND run.event_id = photo.event_id
                          AND run.processor_type = NEW.processor_type
                    ) THEN
                        RAISE EXCEPTION 'processing state run must match its photo and processor'
                            USING ERRCODE = '23514';
                    END IF;
                    IF NEW.current_job_id IS NOT NULL AND NOT EXISTS (
                        SELECT 1
                        FROM processing_processingjob AS job
                        WHERE job.id = NEW.current_job_id
                          AND job.photo_id = NEW.photo_id
                          AND job.processor_type = NEW.processor_type
                          AND (NEW.current_run_id IS NULL OR job.run_id = NEW.current_run_id)
                    ) THEN
                        RAISE EXCEPTION 'processing state job identity mismatch'
                            USING ERRCODE = '23514';
                    END IF;
                    IF NEW.current_attempt_id IS NOT NULL AND NOT EXISTS (
                        SELECT 1
                        FROM processing_processingattempt AS attempt
                        WHERE attempt.id = NEW.current_attempt_id
                          AND attempt.photo_id = NEW.photo_id
                          AND attempt.processor_type = NEW.processor_type
                          AND (NEW.current_job_id IS NULL OR attempt.job_id = NEW.current_job_id)
                          AND (NEW.current_run_id IS NULL OR attempt.run_id = NEW.current_run_id)
                    ) THEN
                        RAISE EXCEPTION 'current processing attempt must match the state identity'
                            USING ERRCODE = '23514';
                    END IF;
                    IF NEW.accepted_attempt_id IS NOT NULL AND NOT EXISTS (
                        SELECT 1
                        FROM processing_processingattempt AS attempt
                        WHERE attempt.id = NEW.accepted_attempt_id
                          AND attempt.photo_id = NEW.photo_id
                          AND attempt.processor_type = NEW.processor_type
                          AND (NEW.current_job_id IS NULL OR attempt.job_id = NEW.current_job_id)
                          AND (NEW.current_run_id IS NULL OR attempt.run_id = NEW.current_run_id)
                    ) THEN
                        RAISE EXCEPTION 'accepted processing attempt must match the state identity'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_state_identity_trg
                BEFORE INSERT OR UPDATE ON processing_photoprocessingstate
                FOR EACH ROW EXECUTE FUNCTION proc_validate_state_identity();

                CREATE FUNCTION proc_guard_state_identity() RETURNS trigger AS $$
                BEGIN
                    IF OLD.photo_id IS DISTINCT FROM NEW.photo_id
                       OR OLD.processor_type IS DISTINCT FROM NEW.processor_type THEN
                        RAISE EXCEPTION 'processing state identity is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_state_identity_guard_trg
                BEFORE UPDATE ON processing_photoprocessingstate
                FOR EACH ROW EXECUTE FUNCTION proc_guard_state_identity();

                CREATE FUNCTION proc_guard_photo_event() RETURNS trigger AS $$
                BEGIN
                    IF NEW.event_id IS DISTINCT FROM OLD.event_id AND (
                        EXISTS (
                            SELECT 1
                            FROM processing_processingjob AS job
                            WHERE job.photo_id = OLD.id
                        )
                        OR EXISTS (
                            SELECT 1
                            FROM processing_photoprocessingstate AS state
                            WHERE state.photo_id = OLD.id
                              AND (
                                  state.current_run_id IS NOT NULL
                                  OR state.current_job_id IS NOT NULL
                                  OR state.current_attempt_id IS NOT NULL
                                  OR state.accepted_attempt_id IS NOT NULL
                              )
                        )
                    ) THEN
                        RAISE EXCEPTION 'photo event is immutable after processing enrollment'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_photo_event_guard_trg
                BEFORE UPDATE OF event_id ON picflow_photo
                FOR EACH ROW EXECUTE FUNCTION proc_guard_photo_event();

                CREATE FUNCTION proc_guard_terminal_attempt() RETURNS trigger AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        IF OLD.status <> 'in_progress' THEN
                            RAISE EXCEPTION 'terminal processing attempts are immutable'
                                USING ERRCODE = '23514';
                        END IF;
                        RETURN OLD;
                    END IF;
                    IF OLD.status <> 'in_progress' THEN
                        RAISE EXCEPTION 'terminal processing attempts are immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_terminal_attempt_guard_trg
                BEFORE UPDATE OR DELETE ON processing_processingattempt
                FOR EACH ROW EXECUTE FUNCTION proc_guard_terminal_attempt();

                CREATE FUNCTION proc_guard_sealed_run_membership() RETURNS trigger AS $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM processing_eventprocessingrun AS run
                        WHERE run.id = OLD.run_id
                          AND run.status IN ('sealed', 'closed')
                    ) THEN
                        RAISE EXCEPTION 'sealed processing run membership is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN OLD;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_sealed_run_membership_guard_trg
                BEFORE DELETE ON processing_processingjob
                FOR EACH ROW EXECUTE FUNCTION proc_guard_sealed_run_membership();

                CREATE FUNCTION proc_guard_closed_run() RETURNS trigger AS $$
                BEGIN
                    IF OLD.status = 'closed' THEN
                        RAISE EXCEPTION 'closed processing runs are immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_closed_run_guard_trg
                BEFORE UPDATE OR DELETE ON processing_eventprocessingrun
                FOR EACH ROW EXECUTE FUNCTION proc_guard_closed_run();

                CREATE FUNCTION proc_guard_late_receipt() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'late processing receipts are immutable'
                        USING ERRCODE = '23514';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_late_receipt_guard_trg
                BEFORE UPDATE OR DELETE ON processing_processinglatereceipt
                FOR EACH ROW EXECUTE FUNCTION proc_guard_late_receipt();

                CREATE FUNCTION proc_guard_conflict_audit() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'processing conflict audits are immutable'
                        USING ERRCODE = '23514';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_conflict_audit_guard_trg
                BEFORE UPDATE OR DELETE ON processing_processingconflictaudit
                FOR EACH ROW EXECUTE FUNCTION proc_guard_conflict_audit();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS proc_conflict_audit_guard_trg
                    ON processing_processingconflictaudit;
                DROP TRIGGER IF EXISTS proc_late_receipt_guard_trg
                    ON processing_processinglatereceipt;
                DROP TRIGGER IF EXISTS proc_closed_run_guard_trg
                    ON processing_eventprocessingrun;
                DROP TRIGGER IF EXISTS proc_sealed_run_membership_guard_trg
                    ON processing_processingjob;
                DROP TRIGGER IF EXISTS proc_terminal_attempt_guard_trg
                    ON processing_processingattempt;
                DROP TRIGGER IF EXISTS proc_photo_event_guard_trg ON picflow_photo;
                DROP TRIGGER IF EXISTS proc_state_identity_guard_trg
                    ON processing_photoprocessingstate;
                DROP TRIGGER IF EXISTS proc_state_identity_trg ON processing_photoprocessingstate;
                DROP TRIGGER IF EXISTS proc_attempt_identity_guard_trg
                    ON processing_processingattempt;
                DROP TRIGGER IF EXISTS proc_attempt_identity_trg ON processing_processingattempt;
                DROP TRIGGER IF EXISTS proc_job_identity_guard_trg ON processing_processingjob;
                DROP TRIGGER IF EXISTS proc_job_identity_trg ON processing_processingjob;
                DROP TRIGGER IF EXISTS proc_run_identity_guard_trg ON processing_eventprocessingrun;
                DROP FUNCTION IF EXISTS proc_guard_photo_event();
                DROP FUNCTION IF EXISTS proc_guard_state_identity();
                DROP FUNCTION IF EXISTS proc_guard_attempt_identity();
                DROP FUNCTION IF EXISTS proc_guard_job_identity();
                DROP FUNCTION IF EXISTS proc_guard_run_identity();
                DROP FUNCTION IF EXISTS proc_guard_conflict_audit();
                DROP FUNCTION IF EXISTS proc_guard_late_receipt();
                DROP FUNCTION IF EXISTS proc_guard_closed_run();
                DROP FUNCTION IF EXISTS proc_guard_sealed_run_membership();
                DROP FUNCTION IF EXISTS proc_guard_terminal_attempt();
                DROP FUNCTION IF EXISTS proc_validate_state_identity();
                DROP FUNCTION IF EXISTS proc_validate_attempt_identity();
                DROP FUNCTION IF EXISTS proc_validate_job_identity();
            """,
        ),
        migrations.RunPython(
            create_legacy_capture_metadata_states,
            remove_processing_states,
        ),
    ]
