# Generated by Django 6.0.6 on 2026-07-29 12:00

import uuid

import django.db.models.deletion
from django.db import migrations, models

import processing.models


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceProcessingAttemptArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="complete",
                        max_length=16,
                    ),
                ),
                (
                    "feature_payload",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                (
                    "quality_payload",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_artifacts",
                        to="processing.processingattempt",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["attempt"], name="proc_face_artifact_attempt_idx"),
                    models.Index(fields=["status"], name="proc_face_artifact_status_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(status__in=("complete", "failed")),
                        name="proc_face_artifact_status_chk",
                    ),
                    models.UniqueConstraint(
                        fields=("attempt",),
                        name="proc_face_artifact_attempt_uniq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PhotoFaceDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "face_index",
                    models.PositiveSmallIntegerField(),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("kept", "Kept"),
                            ("failed", "Failed"),
                        ],
                        default="detected",
                        max_length=16,
                    ),
                ),
                (
                    "geometry",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_detections",
                        to="processing.processingattempt",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detections",
                        to="processing.faceprocessingattemptartifact",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["attempt", "face_index"], name="proc_face_detect_attempt_idx"
                    ),
                    models.Index(fields=["status"], name="proc_face_detection_status_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            status__in=(
                                "detected",
                                "kept",
                                "failed",
                            )
                        ),
                        name="proc_photo_face_detection_status_chk",
                    ),
                    models.UniqueConstraint(
                        fields=("attempt", "face_index"),
                        name="proc_photo_face_detection_attempt_face_idx_uniq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FaceEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("model_version", models.CharField(blank=True, default="", max_length=64)),
                (
                    "vector",
                    models.JSONField(
                        default=list, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "detection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="embedding",
                        to="processing.photofacedetection",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["detection"], name="proc_face_embed_detection_idx"),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION proc_validate_face_attempt_artifact_terminal() RETURNS trigger AS $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM processing_processingattempt AS attempt
                        WHERE attempt.id = NEW.attempt_id
                          AND attempt.status IN ('succeeded', 'failed', 'expired', 'stale')
                    ) THEN
                        RAISE EXCEPTION 'face attempt artifacts are terminal-only'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_face_attempt_artifact_terminal_trg
                    BEFORE INSERT OR UPDATE ON processing_faceprocessingattemptartifact
                    FOR EACH ROW
                    EXECUTE FUNCTION proc_validate_face_attempt_artifact_terminal();

                CREATE FUNCTION proc_guard_face_attempt_artifact_immutability()
                RETURNS trigger AS $$
                BEGIN
                    IF TG_OP IN ('UPDATE', 'DELETE')
                       AND EXISTS (
                           SELECT 1
                           FROM processing_processingattempt AS attempt
                           WHERE attempt.id = OLD.attempt_id
                             AND attempt.status IN ('succeeded', 'failed', 'expired', 'stale')
                       ) THEN
                        RAISE EXCEPTION 'terminal face attempt artifacts are immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    IF TG_OP = 'DELETE' THEN
                        RETURN OLD;
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_face_attempt_artifact_immutability_trg
                    BEFORE UPDATE OR DELETE ON processing_faceprocessingattemptartifact
                    FOR EACH ROW
                    EXECUTE FUNCTION proc_guard_face_attempt_artifact_immutability();

                CREATE FUNCTION proc_validate_face_detection_terminal() RETURNS trigger AS $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM processing_processingattempt AS attempt
                        WHERE attempt.id = NEW.attempt_id
                          AND attempt.status IN ('succeeded', 'failed', 'expired', 'stale')
                    ) THEN
                        RAISE EXCEPTION 'face detections are terminal-only'
                            USING ERRCODE = '23514';
                    END IF;
                    IF NOT EXISTS (
                        SELECT 1
                        FROM processing_faceprocessingattemptartifact AS artifact
                        WHERE artifact.id = NEW.artifact_id
                          AND artifact.attempt_id = NEW.attempt_id
                    ) THEN
                        RAISE EXCEPTION 'face detection artifact must match attempt'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_face_detection_terminal_trg
                    BEFORE INSERT OR UPDATE ON processing_photofacedetection
                    FOR EACH ROW
                    EXECUTE FUNCTION proc_validate_face_detection_terminal();

                CREATE FUNCTION proc_guard_face_detection_immutability() RETURNS trigger AS $$
                BEGIN
                    IF TG_OP IN ('UPDATE', 'DELETE')
                       AND EXISTS (
                           SELECT 1
                           FROM processing_processingattempt AS attempt
                           WHERE attempt.id = OLD.attempt_id
                             AND attempt.status IN ('succeeded', 'failed', 'expired', 'stale')
                       ) THEN
                        RAISE EXCEPTION 'terminal face detections are immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    IF TG_OP = 'DELETE' THEN
                        RETURN OLD;
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_face_detection_immutability_trg
                    BEFORE UPDATE OR DELETE ON processing_photofacedetection
                    FOR EACH ROW
                    EXECUTE FUNCTION proc_guard_face_detection_immutability();

                CREATE FUNCTION proc_validate_face_embedding_terminal() RETURNS trigger AS $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM processing_photofacedetection AS detection
                        JOIN processing_faceprocessingattemptartifact AS artifact
                          ON artifact.id = detection.artifact_id
                        JOIN processing_processingattempt AS attempt
                          ON attempt.id = detection.attempt_id
                        WHERE detection.id = NEW.detection_id
                          AND attempt.status IN ('succeeded', 'failed', 'expired', 'stale')
                    ) THEN
                        RAISE EXCEPTION 'face embeddings are terminal-only'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_face_embedding_terminal_trg
                    BEFORE INSERT OR UPDATE ON processing_faceembedding
                    FOR EACH ROW
                    EXECUTE FUNCTION proc_validate_face_embedding_terminal();

                CREATE FUNCTION proc_guard_face_embedding_immutability() RETURNS trigger AS $$
                BEGIN
                    IF TG_OP IN ('UPDATE', 'DELETE')
                       AND EXISTS (
                           SELECT 1
                           FROM processing_photofacedetection AS detection
                           JOIN processing_faceprocessingattemptartifact AS artifact
                             ON artifact.id = detection.artifact_id
                           JOIN processing_processingattempt AS attempt
                             ON attempt.id = detection.attempt_id
                           WHERE detection.id = OLD.detection_id
                             AND attempt.status IN ('succeeded', 'failed', 'expired', 'stale')
                       ) THEN
                        RAISE EXCEPTION 'terminal face embeddings are immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    IF TG_OP = 'DELETE' THEN
                        RETURN OLD;
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_face_embedding_immutability_trg
                    BEFORE UPDATE OR DELETE ON processing_faceembedding
                    FOR EACH ROW
                    EXECUTE FUNCTION proc_guard_face_embedding_immutability();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS proc_face_embedding_immutability_trg
                ON processing_faceembedding;
                DROP FUNCTION IF EXISTS proc_guard_face_embedding_immutability();
                DROP TRIGGER IF EXISTS proc_face_embedding_terminal_trg ON processing_faceembedding;
                DROP FUNCTION IF EXISTS proc_validate_face_embedding_terminal();
                DROP TRIGGER IF EXISTS proc_face_detection_immutability_trg
                ON processing_photofacedetection;
                DROP FUNCTION IF EXISTS proc_guard_face_detection_immutability();
                DROP TRIGGER IF EXISTS proc_face_detection_terminal_trg
                ON processing_photofacedetection;
                DROP FUNCTION IF EXISTS proc_validate_face_detection_terminal();
                DROP TRIGGER IF EXISTS proc_face_attempt_artifact_immutability_trg
                    ON processing_faceprocessingattemptartifact;
                DROP FUNCTION IF EXISTS proc_guard_face_attempt_artifact_immutability();
                DROP TRIGGER IF EXISTS proc_face_attempt_artifact_terminal_trg
                    ON processing_faceprocessingattemptartifact;
                DROP FUNCTION IF EXISTS proc_validate_face_attempt_artifact_terminal();
            """,
        ),
    ]
