# Generated by Django 6.0.6 on 2026-07-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picflow", "0006_photo_processing_policy"),
        ("processing", "0002_add_face_embedding_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoDerivative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant", models.CharField(max_length=64)),
                ("final_key", models.CharField(max_length=255, unique=True)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("oriented_source_width", models.PositiveIntegerField()),
                ("oriented_source_height", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accepted_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_derivatives",
                        to="processing.processingattempt",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derivatives",
                        to="picflow.photo",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(content_type="image/jpeg"),
                        name="proc_photo_derivative_jpeg_chk",
                    ),
                    models.UniqueConstraint(
                        fields=("photo", "variant"),
                        name="proc_photo_derivative_photo_variant_uniq",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION proc_guard_photo_derivative_immutability() RETURNS trigger AS $$
                BEGIN
                    IF TG_OP = 'INSERT' THEN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM processing_processingattempt AS attempt
                            WHERE attempt.id = NEW.accepted_attempt_id
                              AND attempt.photo_id = NEW.photo_id
                              AND attempt.processor_type = 'generate_preview'
                              AND attempt.status = 'succeeded'
                              AND attempt.accepted IS TRUE
                        ) THEN
                            RAISE EXCEPTION
                                'derivatives require an accepted successful preview attempt'
                                USING ERRCODE = '23514';
                        END IF;
                        RETURN NEW;
                    END IF;
                    RAISE EXCEPTION 'published photo derivatives are immutable'
                        USING ERRCODE = '23514';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_photo_derivative_immutability_trg
                    BEFORE INSERT OR UPDATE OR DELETE ON processing_photoderivative
                    FOR EACH ROW
                    EXECUTE FUNCTION proc_guard_photo_derivative_immutability();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS proc_photo_derivative_immutability_trg
                    ON processing_photoderivative;
                DROP FUNCTION IF EXISTS proc_guard_photo_derivative_immutability();
            """,
        ),
    ]
