# Generated by Django 6.0.6 on 2026-08-05 05:22

import uuid

import django.db.models.deletion
from django.db import migrations, models

import processing.models


class Migration(migrations.Migration):
    dependencies = [
        ("picflow", "0006_photo_processing_policy"),
        ("processing", "0005_alter_processingattempt_result"),
    ]
    operations = [
        migrations.CreateModel(
            name="FaceClusterCorpus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("failed", "Failed"),
                            ("published", "Published"),
                        ],
                        default="building",
                        max_length=16,
                    ),
                ),
                ("algorithm_version", models.CharField(max_length=64)),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                ("configuration_hash", models.CharField(max_length=64)),
                ("contract_version", models.PositiveSmallIntegerField()),
                ("processor_type", models.CharField(max_length=64)),
                ("processor_version", models.PositiveSmallIntegerField()),
                ("model_version", models.CharField(max_length=64)),
                ("embedding_dimensions", models.PositiveSmallIntegerField()),
                ("edge_threshold", models.FloatField()),
                ("representative_threshold", models.FloatField()),
                ("distance_block_size", models.PositiveIntegerField()),
                ("max_candidate_edges", models.PositiveIntegerField()),
                ("input_count", models.PositiveIntegerField(default=0)),
                ("cluster_count", models.PositiveIntegerField(default=0)),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("singleton_count", models.PositiveIntegerField(default=0)),
                ("candidate_edge_count", models.PositiveIntegerField(default=0)),
                ("build_duration_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("peak_memory_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("input_hash", models.CharField(blank=True, default="", max_length=64)),
                ("membership_hash", models.CharField(blank=True, default="", max_length=64)),
                ("failure_code", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_cluster_corpora",
                        to="picflow.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaceCluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cluster_key", models.CharField(max_length=64)),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_clusters",
                        to="picflow.event",
                    ),
                ),
                (
                    "representative_detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="representative_face_clusters",
                        to="processing.photofacedetection",
                    ),
                ),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clusters",
                        to="processing.faceclustercorpus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventFaceClusterActivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("anchor_threshold", models.FloatField()),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                ("configuration_hash", models.CharField(max_length=64)),
                ("approved_evaluation_report_hash", models.CharField(max_length=64)),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_cluster_activations",
                        to="picflow.event",
                    ),
                ),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_activations",
                        to="processing.faceclustercorpus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaceClusterMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("member_index", models.PositiveIntegerField()),
                ("distance_to_representative", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="processing.facecluster",
                    ),
                ),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="processing.faceclustercorpus",
                    ),
                ),
                (
                    "detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_cluster_memberships",
                        to="processing.photofacedetection",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_cluster_members",
                        to="picflow.event",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="faceclustercorpus",
            index=models.Index(fields=["event", "status"], name="face_corpus_event_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="faceclustercorpus",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("building", "failed", "published"))),
                name="face_corpus_status_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="faceclustercorpus",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="face_corpus_version_chk"
            ),
        ),
        migrations.AddConstraint(
            model_name="faceclustercorpus",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("edge_threshold__gte", 0),
                    ("edge_threshold__lte", 2),
                    ("representative_threshold__gte", 0),
                    ("representative_threshold__lte", 2),
                ),
                name="face_corpus_threshold_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="faceclustercorpus",
            constraint=models.UniqueConstraint(
                fields=("event", "version"), name="face_corpus_event_version_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="facecluster",
            index=models.Index(fields=["event", "corpus"], name="face_cluster_event_corpus_idx"),
        ),
        migrations.AddConstraint(
            model_name="facecluster",
            constraint=models.UniqueConstraint(
                fields=("corpus", "cluster_key"), name="face_cluster_corpus_key_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventfaceclusteractivation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("event",),
                name="face_activation_event_active_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventfaceclusteractivation",
            constraint=models.CheckConstraint(
                condition=models.Q(("anchor_threshold__gte", 0), ("anchor_threshold__lte", 2)),
                name="face_activation_anchor_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="faceclustermember",
            index=models.Index(
                fields=["event", "corpus", "detection"], name="face_member_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="faceclustermember",
            constraint=models.UniqueConstraint(
                fields=("cluster", "detection"), name="face_member_cluster_detection_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="faceclustermember",
            constraint=models.UniqueConstraint(
                fields=("corpus", "detection"), name="face_member_corpus_detection_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="faceclustermember",
            constraint=models.UniqueConstraint(
                fields=("cluster", "member_index"), name="face_member_cluster_index_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="faceclustermember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("distance_to_representative__gte", 0), ("distance_to_representative__lte", 2)
                ),
                name="face_member_distance_chk",
            ),
        ),
    ]
