# Generated by Django 6.0.6 on 2026-08-08

import uuid
from itertools import batched

import django.db.models.deletion
from django.db import migrations, models


def backfill_face_embedding_projections(apps, schema_editor):  # noqa: ARG001
    State = apps.get_model("processing", "PhotoProcessingState")
    Projection = apps.get_model("processing", "PhotoFaceEmbeddingProjection")
    rows = (
        State.objects.filter(
            processor_type="face_embedding",
            accepted_attempt_id__isnull=False,
            accepted_attempt__processor_type="face_embedding",
            accepted_attempt__status="succeeded",
            accepted_attempt__accepted=True,
        )
        .values_list(
            "photo_id",
            "accepted_attempt_id",
            "accepted_attempt__contract_version",
            "accepted_attempt__processor_version",
            "accepted_attempt__job__configuration_hash",
        )
        .iterator(chunk_size=500)
    )
    for batch in batched(rows, 500):
        Projection.objects.bulk_create(
            [
                Projection(
                    photo_id=photo_id,
                    accepted_attempt_id=attempt_id,
                    contract_version=contract_version,
                    processor_version=processor_version,
                    configuration_hash=configuration_hash,
                )
                for (
                    photo_id,
                    attempt_id,
                    contract_version,
                    processor_version,
                    configuration_hash,
                ) in batch
            ],
            batch_size=500,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0006_face_cluster_corpus"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoFaceEmbeddingProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contract_version", models.PositiveSmallIntegerField()),
                ("processor_version", models.PositiveSmallIntegerField()),
                ("configuration_hash", models.CharField(max_length=64)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accepted_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_embedding_projections",
                        to="processing.processingattempt",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="face_embedding_projections",
                        to="picflow.photo",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["accepted_attempt"], name="proc_face_proj_attempt_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "photo",
                            "contract_version",
                            "processor_version",
                            "configuration_hash",
                        ),
                        name="proc_face_proj_generation_uniq",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION proc_validate_face_projection() RETURNS trigger AS $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM processing_processingattempt AS attempt
                        JOIN processing_processingjob AS job ON job.id = attempt.job_id
                        JOIN processing_eventprocessingrun AS run ON run.id = attempt.run_id
                        WHERE attempt.id = NEW.accepted_attempt_id
                          AND attempt.photo_id = NEW.photo_id
                          AND attempt.processor_type = 'face_embedding'
                          AND attempt.contract_version = NEW.contract_version
                          AND attempt.processor_version = NEW.processor_version
                          AND attempt.status = 'succeeded'
                          AND attempt.accepted IS TRUE
                          AND job.contract_version = NEW.contract_version
                          AND job.processor_type = 'face_embedding'
                          AND job.processor_version = NEW.processor_version
                          AND job.configuration_hash = NEW.configuration_hash
                          AND run.contract_version = NEW.contract_version
                          AND run.processor_type = 'face_embedding'
                          AND run.processor_version = NEW.processor_version
                          AND run.configuration_hash = NEW.configuration_hash
                    ) THEN
                        RAISE EXCEPTION
                            'face projection requires an accepted exact-generation face attempt'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_face_projection_validate_trg
                    BEFORE INSERT OR UPDATE ON processing_photofaceembeddingprojection
                    FOR EACH ROW
                    EXECUTE FUNCTION proc_validate_face_projection();

                CREATE FUNCTION proc_guard_face_projection_identity() RETURNS trigger AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION 'face projections are immutable and cannot be deleted'
                            USING ERRCODE = '23514';
                    END IF;
                    IF OLD.photo_id IS DISTINCT FROM NEW.photo_id
                       OR OLD.contract_version IS DISTINCT FROM NEW.contract_version
                       OR OLD.processor_version IS DISTINCT FROM NEW.processor_version
                       OR OLD.configuration_hash IS DISTINCT FROM NEW.configuration_hash THEN
                        RAISE EXCEPTION 'face projection generation identity is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_face_projection_identity_guard_trg
                    BEFORE UPDATE OR DELETE ON processing_photofaceembeddingprojection
                    FOR EACH ROW
                    EXECUTE FUNCTION proc_guard_face_projection_identity();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS proc_face_projection_identity_guard_trg
                    ON processing_photofaceembeddingprojection;
                DROP FUNCTION IF EXISTS proc_guard_face_projection_identity();
                DROP TRIGGER IF EXISTS proc_face_projection_validate_trg
                    ON processing_photofaceembeddingprojection;
                DROP FUNCTION IF EXISTS proc_validate_face_projection();
            """,
        ),
        migrations.RunPython(
            backfill_face_embedding_projections,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="photofacedetection",
            name="status",
            field=models.CharField(
                choices=[
                    ("detected", "Detected"),
                    ("kept", "Kept"),
                    ("quality_rejected", "Quality rejected"),
                    ("failed", "Failed"),
                ],
                default="detected",
                max_length=16,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="photofacedetection",
            name="proc_photo_face_detection_status_chk",
        ),
        migrations.AddConstraint(
            model_name="photofacedetection",
            constraint=models.CheckConstraint(
                condition=models.Q(status__in=("detected", "kept", "quality_rejected", "failed")),
                name="proc_photo_face_detection_status_chk",
            ),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION proc_validate_face_embedding_quality_status() RETURNS trigger AS $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM processing_photofacedetection AS detection
                        WHERE detection.id = NEW.detection_id
                          AND detection.status = 'quality_rejected'
                    ) THEN
                        RAISE EXCEPTION 'quality-rejected face detections cannot own embeddings'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_face_embedding_quality_status_trg
                    BEFORE INSERT OR UPDATE OF detection_id ON processing_faceembedding
                    FOR EACH ROW
                    EXECUTE FUNCTION proc_validate_face_embedding_quality_status();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS proc_face_embedding_quality_status_trg
                    ON processing_faceembedding;
                DROP FUNCTION IF EXISTS proc_validate_face_embedding_quality_status();
            """,
        ),
    ]
