# Generated by Django 6.0.6 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0006_face_cluster_corpus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photofacedetection",
            name="status",
            field=models.CharField(
                choices=[
                    ("detected", "Detected"),
                    ("kept", "Kept"),
                    ("quality_rejected", "Quality rejected"),
                    ("failed", "Failed"),
                ],
                default="detected",
                max_length=16,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="photofacedetection",
            name="proc_photo_face_detection_status_chk",
        ),
        migrations.AddConstraint(
            model_name="photofacedetection",
            constraint=models.CheckConstraint(
                condition=models.Q(status__in=("detected", "kept", "quality_rejected", "failed")),
                name="proc_photo_face_detection_status_chk",
            ),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION proc_validate_face_embedding_quality_status() RETURNS trigger AS $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM processing_photofacedetection AS detection
                        WHERE detection.id = NEW.detection_id
                          AND detection.status = 'quality_rejected'
                    ) THEN
                        RAISE EXCEPTION 'quality-rejected face detections cannot own embeddings'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER proc_face_embedding_quality_status_trg
                    BEFORE INSERT OR UPDATE OF detection_id ON processing_faceembedding
                    FOR EACH ROW
                    EXECUTE FUNCTION proc_validate_face_embedding_quality_status();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS proc_face_embedding_quality_status_trg
                    ON processing_faceembedding;
                DROP FUNCTION IF EXISTS proc_validate_face_embedding_quality_status();
            """,
        ),
    ]
