# Generated by Django 6.0.6 on 2026-09-27 19:09

import uuid

import django.db.models.deletion
import django.db.models.lookups
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension

import processing.models


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0010_face_projection_generation_index"),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="FaceEmbeddingVector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("model_version", models.CharField(max_length=64)),
                ("vector", pgvector.django.vector.VectorField()),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, validators=[processing.models.validate_bounded_json]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "detection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="embedding_vector",
                        to="processing.photofacedetection",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("model_version", "sface"),
                                django.db.models.lookups.Exact(
                                    models.Func(
                                        "vector",
                                        function="vector_dims",
                                        output_field=models.IntegerField(),
                                    ),
                                    models.Value(128),
                                ),
                            ),
                            models.Q(
                                ("model_version", "adaface-ir18-webface4m"),
                                django.db.models.lookups.Exact(
                                    models.Func(
                                        "vector",
                                        function="vector_dims",
                                        output_field=models.IntegerField(),
                                    ),
                                    models.Value(512),
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="proc_vector_model_dimension",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            django.db.models.lookups.GreaterThanOrEqual(
                                models.Func(
                                    "vector",
                                    function="vector_norm",
                                    output_field=models.FloatField(),
                                ),
                                models.Value(0.9999989),
                            ),
                            django.db.models.lookups.LessThanOrEqual(
                                models.Func(
                                    "vector",
                                    function="vector_norm",
                                    output_field=models.FloatField(),
                                ),
                                models.Value(1.0000011),
                            ),
                        ),
                        name="proc_vector_unit_norm",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION proc_validate_vector_evidence() RETURNS trigger AS $$
                BEGIN
                    IF TG_OP <> 'INSERT' THEN
                        RAISE EXCEPTION 'face vector evidence is immutable' USING ERRCODE = '23514';
                    END IF;
                    IF NOT EXISTS (
                        SELECT 1 FROM processing_photofacedetection detection
                        JOIN processing_processingattempt attempt
                            ON attempt.id = detection.attempt_id
                        WHERE detection.id = NEW.detection_id AND detection.status = 'kept'
                        AND attempt.status = 'succeeded' AND attempt.accepted
                        AND attempt.processor_type = 'face_embedding'
                    ) THEN
                        RAISE EXCEPTION 'vector evidence requires an accepted kept face'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER proc_vector_evidence_trg
                    BEFORE INSERT OR UPDATE OR DELETE ON processing_faceembeddingvector
                    FOR EACH ROW EXECUTE FUNCTION proc_validate_vector_evidence();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS proc_vector_evidence_trg ON processing_faceembeddingvector;
                DROP FUNCTION IF EXISTS proc_validate_vector_evidence();
            """,
        ),
    ]
