# Generated by Django 6.0.6 on 2026-09-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0010_face_projection_generation_index"),
        ("selfie_search", "0005_optional_feedback_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("bulk", "Bulk"), ("selfie", "Selfie")], max_length=6, unique=True
                    ),
                ),
                ("group_id", models.CharField(max_length=64)),
                ("active_build", models.CharField(max_length=40)),
                ("staged_build", models.CharField(default=None, max_length=40, null=True)),
                ("claims_paused", models.BooleanField(default=True)),
                ("local_claims_paused", models.BooleanField(default=False)),
                ("observation_sequence", models.PositiveBigIntegerField(default=0)),
                ("observation_started_at", models.DateTimeField(default=None, null=True)),
                ("observation_completed_at", models.DateTimeField(default=None, null=True)),
                ("target_size", models.PositiveSmallIntegerField(default=0)),
                ("observed_members", models.JSONField(default=list)),
                ("queue_observed_at", models.DateTimeField(default=None, null=True)),
                ("endpoint_available", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("name__in", ("bulk", "selfie"))),
                        name="worker_pool_name_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("target_size__lte", 2)), name="worker_pool_target_chk"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("staged_build__isnull", True),
                            models.Q(("staged_build", models.F("active_build")), _negated=True),
                            _connector="OR",
                        ),
                        name="worker_pool_builds_differ_chk",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkerPoolMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("instance_id", models.CharField(max_length=64, unique=True)),
                ("boot_id", models.UUIDField()),
                ("registration_generation", models.UUIDField(default=None, null=True)),
                ("worker_build", models.CharField(max_length=40)),
                ("ready", models.BooleanField(default=False)),
                ("draining", models.BooleanField(default=False)),
                ("heartbeat_at", models.DateTimeField(default=None, null=True)),
                ("idle_since", models.DateTimeField(default=None, null=True)),
                ("retirement_grant", models.UUIDField(default=None, null=True)),
                ("granted_at", models.DateTimeField(default=None, null=True)),
                (
                    "grant_observation_sequence",
                    models.PositiveBigIntegerField(default=None, null=True),
                ),
                ("reconciled_at", models.DateTimeField(default=None, null=True)),
                (
                    "active_processing_attempt",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pool_member",
                        to="processing.processingattempt",
                    ),
                ),
                (
                    "active_selfie_attempt",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pool_member",
                        to="selfie_search.selfiesearchattempt",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="processing.workerpool",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("active_processing_attempt__isnull", True),
                            ("active_selfie_attempt__isnull", True),
                            _connector="OR",
                        ),
                        name="worker_member_one_attempt_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("grant_observation_sequence__isnull", True),
                                ("granted_at__isnull", True),
                                ("retirement_grant__isnull", True),
                            ),
                            models.Q(
                                ("draining", True),
                                ("grant_observation_sequence__isnull", False),
                                ("granted_at__isnull", False),
                                ("ready", False),
                                ("retirement_grant__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="worker_member_grant_fields_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reconciled_at__isnull", True),
                            ("retirement_grant__isnull", False),
                            _connector="OR",
                        ),
                        name="worker_member_reconciled_chk",
                    ),
                ],
            },
        ),
    ]
