# Generated by Django 6.0.6 on 2026-10-01 05:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picflow", "0016_gallery_media_projection"),
        ("processing", "0013_worker_pool_telemetry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BibReadingChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "before_number",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(regex="\\A[0-9]{1,16}\\Z")
                        ],
                    ),
                ),
                (
                    "after_number",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(regex="\\A[0-9]{1,16}\\Z")
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bib_reading_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bib_reading_changes",
                        to="picflow.photo",
                    ),
                ),
                (
                    "source_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bib_reading_changes",
                        to="processing.processingattempt",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("after_number__isnull", False), ("before_number__isnull", True)
                            ),
                            models.Q(
                                ("after_number__isnull", True), ("before_number__isnull", False)
                            ),
                            models.Q(
                                ("after_number__isnull", False),
                                ("before_number__isnull", False),
                                models.Q(
                                    ("before_number", models.F("after_number")), _negated=True
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="proc_bib_change_shape_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("before_number__isnull", True),
                            ("before_number__regex", "^[0-9]{1,16}$"),
                            _connector="OR",
                        ),
                        name="proc_bib_change_before_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("after_number__isnull", True),
                            ("after_number__regex", "^[0-9]{1,16}$"),
                            _connector="OR",
                        ),
                        name="proc_bib_change_after_chk",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION proc_guard_bib_reading_change() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'bib reading changes are immutable' USING ERRCODE = '23514';
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER proc_bib_reading_change_immutable
                BEFORE UPDATE OR DELETE ON processing_bibreadingchange
                FOR EACH ROW EXECUTE FUNCTION proc_guard_bib_reading_change();
            """,
            reverse_sql="""
                DROP TRIGGER proc_bib_reading_change_immutable ON processing_bibreadingchange;
                DROP FUNCTION proc_guard_bib_reading_change();
            """,
        ),
    ]
