"""Host-bound fleet readiness and bounded signal drain, without worker privileges."""

from __future__ import annotations

import os
import re
import signal
import threading
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING
from uuid import UUID

from photo_worker.client import ApiError, HttpClient
from photo_worker.transport import POOL_IDENTITIES

if TYPE_CHECKING:
    from photo_worker.runner import Worker


@dataclass(frozen=True)
class HostIdentity:
    pool: str
    instance_id: str
    boot_id: str
    worker_build: str

    def __post_init__(self) -> None:
        if (
            self.pool not in POOL_IDENTITIES
            or re.fullmatch(r"[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}", self.instance_id) is None
            or re.fullmatch(r"[0-9a-f]{40}", self.worker_build) is None
        ):
            raise ValueError("invalid worker host identity")
        if str(UUID(self.boot_id)) != self.boot_id:
            raise ValueError("invalid worker host boot identity")

    @classmethod
    def read(
        cls,
        *,
        pool: str,
        build: str,
        boot_path: Path = Path("/run/findme-worker/boot-id"),
        instance_path: Path = Path("/run/findme-worker/instance-id"),
    ) -> HostIdentity:
        # Both files are host-owned and mounted read-only, never generated by this process.
        return cls(pool, instance_path.read_text().strip(), boot_path.read_text().strip(), build)

    def envelope(self) -> dict[str, str]:
        return {
            "pool": self.pool,
            "instance_id": self.instance_id,
            "boot_id": self.boot_id,
            "worker_build": self.worker_build,
        }


class DrainController:
    """One irreversible drain and one deadline, shared by server and signal requests."""

    def __init__(
        self,
        *,
        completed: threading.Event | None = None,
        timeout_seconds: float = 900,
        force_exit: Callable[[int], object] = os._exit,
    ) -> None:
        if not 0 < timeout_seconds <= 900:
            raise ValueError("drain timeout must be between 0 and 900 seconds")
        self.requested = threading.Event()
        self.completed = completed or threading.Event()
        self._lock = threading.RLock()
        self._timeout = timeout_seconds
        self._force_exit = force_exit

    def request(self) -> None:
        with self._lock:
            if self.requested.is_set():
                return
            self.requested.set()
            threading.Thread(target=self._deadline, daemon=True).start()

    def _deadline(self) -> None:
        if not self.completed.wait(self._timeout):
            # Stop a hung attempt's renewal; durable lease recovery stays authoritative.
            self._force_exit(1)


class FleetLifecycle:
    def __init__(
        self,
        client: HttpClient,
        identity: HostIdentity,
        drain: DrainController,
        *,
        warmup: Callable[[], None] | None = None,
        startup_timeout_seconds: float = 300,
        force_exit: Callable[[int], object] = os._exit,
    ) -> None:
        if not 0 < startup_timeout_seconds <= 300:
            raise ValueError("startup timeout must be between 0 and 300 seconds")
        self._client = client
        self._identity = identity
        self._drain = drain
        self._draining = drain.requested
        self._closed = threading.Event()
        self._warm = False
        self._admitted = False
        self._warmup = warmup or _warm_models
        self._thread: threading.Thread | None = None
        self._state_lock = threading.RLock()
        self._startup_timeout = startup_timeout_seconds
        self._force_exit = force_exit

    @property
    def can_claim(self) -> bool:
        return (
            self._warm
            and self._admitted
            and not self._draining.is_set()
            and not self._closed.is_set()
        )

    def start(self) -> None:
        started = threading.Event()

        def deadline() -> None:
            if not started.wait(self._startup_timeout):
                self._closed.set()
                self._force_exit(1)

        threading.Thread(target=deadline, daemon=True).start()
        try:
            self._client.bind_member(self._identity.envelope())
            self._startup_retry(lambda: self._client.member_request("register"))
            if self._draining.is_set() or self._closed.is_set():
                return
            self._warmup()
            if not self._draining.is_set() and not self._closed.is_set():
                self._warm = True
                self._startup_retry(self.pulse)
                self._thread = threading.Thread(target=self._run, daemon=True)
                self._thread.start()
        finally:
            started.set()

    def _startup_retry(self, operation: Callable[[], object]) -> None:
        while not self._draining.is_set() and not self._closed.is_set():
            try:
                with self._state_lock:
                    operation()
                return
            except ApiError as error:
                if not error.retryable:
                    raise
                self._closed.wait(1)

    def pulse(self) -> None:
        with self._state_lock:
            self._admitted = False
            try:
                result = self._send_heartbeat()
            except ApiError as error:
                if error.code != "registration_changed" or self._draining.is_set():
                    raise
                # A delayed registration from another process may supersede this one.
                # Recover once per pulse; no unbounded retry or interruption of job keeper.
                self._client.member_request("register")
                result = self._send_heartbeat()
            if result.get("draining") is True:
                self._drain.request()
            self._admitted = result.get("ready") is True

    def _send_heartbeat(self) -> dict:
        return self._client.member_request(
            "heartbeat",
            ready=self._warm and not self._draining.is_set(),
            draining=self._draining.is_set(),
        )

    def _run(self) -> None:
        while not self._closed.wait(15):
            try:
                self.pulse()
            except ApiError:
                self._admitted = False

    def close(self) -> None:
        self._closed.set()
        # Member heartbeat is independent of the attempt keeper and never holds up callbacks.
        if self._thread is not None:
            self._thread.join(timeout=1)


def _warm_models() -> None:
    from photo_worker.face_embedding import warm_models

    warm_models()


def install_signal_handlers(worker: Worker) -> None:
    def drain(_signum: int, _frame: object) -> None:
        worker.request_drain()

    signal.signal(signal.SIGTERM, drain)
    signal.signal(signal.SIGINT, drain)
