from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "check_migration_immutability.py"

_HISTORICAL_OPTIONAL_CONTACT = """# Generated by Django 6.0.6 on 2026-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selfie_search", "0002_selfiesearchfeedback_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfiesearchfeedback",
            name="contact",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.RemoveConstraint(
            model_name="selfiesearchfeedback",
            name="selfie_feedback_contact_nonempty_chk",
        ),
    ]
"""

_RENAMED_OPTIONAL_CONTACT = """# Generated by Django 6.0.6 on 2026-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selfie_search", "0004_remove_selfie_search_candidate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfiesearchfeedback",
            name="contact",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.RemoveConstraint(
            model_name="selfiesearchfeedback",
            name="selfie_feedback_contact_nonempty_chk",
        ),
    ]
"""

_RECOVERY_MERGE = """from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("selfie_search", "0003_optional_feedback_contact"),
        ("selfie_search", "0004_remove_selfie_search_candidate"),
    ]

    operations: list[migrations.operations.base.Operation] = []
"""


def _run(*args: str, cwd: Path, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args,
        cwd=cwd,
        check=check,
        capture_output=True,
        text=True,
    )


def _commit(repository: Path, message: str) -> str:
    _run("git", "add", ".", cwd=repository)
    _run("git", "commit", "-qm", message, cwd=repository)
    return _run("git", "rev-parse", "HEAD", cwd=repository).stdout.strip()


def _repository(tmp_path: Path) -> tuple[Path, str]:
    repository = tmp_path / "repository"
    migrations = repository / "src/backend/catalog/migrations"
    migrations.mkdir(parents=True)
    _run("git", "init", "-q", cwd=repository)
    _run("git", "config", "user.name", "Migration Test", cwd=repository)
    _run("git", "config", "user.email", "migration-test@example.com", cwd=repository)
    (migrations / "__init__.py").write_text("", encoding="utf-8")
    (migrations / "0001_initial.py").write_text("BASE = True\n", encoding="utf-8")
    (repository / "src/backend/catalog/models.py").write_text("MODEL = True\n", encoding="utf-8")
    return repository, _commit(repository, "base migrations")


def _check(repository: Path, base: str, head: str) -> subprocess.CompletedProcess[str]:
    return _run(
        sys.executable,
        str(SCRIPT),
        "--base",
        base,
        "--head",
        head,
        cwd=repository,
        check=False,
    )


def _selfie_search_recovery_repository(tmp_path: Path) -> tuple[Path, str]:
    repository = tmp_path / "repository"
    migrations = repository / "src/backend/selfie_search/migrations"
    migrations.mkdir(parents=True)
    _run("git", "init", "-q", cwd=repository)
    _run("git", "config", "user.name", "Migration Test", cwd=repository)
    _run("git", "config", "user.email", "migration-test@example.com", cwd=repository)
    (migrations / "0002_selfiesearchfeedback_and_more.py").write_text(
        "BASE = True\n", encoding="utf-8"
    )
    (migrations / "0005_optional_feedback_contact.py").write_text(
        _RENAMED_OPTIONAL_CONTACT, encoding="utf-8"
    )
    return repository, _commit(repository, "renamed optional contact migration")


def test_allows_new_leaf_merge_and_non_migration_python_files(tmp_path: Path) -> None:
    repository, base = _repository(tmp_path)
    migrations = repository / "src/backend/catalog/migrations"
    (migrations / "0002_add_caption.py").write_text("LEAF = True\n", encoding="utf-8")
    (migrations / "0003_merge_0002_add_caption_0002_other.py").write_text(
        "MERGE = True\n", encoding="utf-8"
    )
    (migrations / "__init__.py").write_text("# package\n", encoding="utf-8")
    (repository / "src/backend/catalog/models.py").write_text("MODEL = False\n", encoding="utf-8")
    head = _commit(repository, "add migrations")

    result = _check(repository, base, head)

    assert result.returncode == 0
    assert result.stdout == ""
    assert result.stderr == ""


def test_rejects_modified_base_migration_with_its_path(tmp_path: Path) -> None:
    repository, base = _repository(tmp_path)
    migration = repository / "src/backend/catalog/migrations/0001_initial.py"
    migration.write_text("BASE = False\n", encoding="utf-8")
    head = _commit(repository, "modify base migration")

    result = _check(repository, base, head)

    assert result.returncode == 1
    assert result.stdout == "src/backend/catalog/migrations/0001_initial.py\n"
    assert result.stderr == ""


def test_rejects_deleted_base_migration_with_its_path(tmp_path: Path) -> None:
    repository, base = _repository(tmp_path)
    (repository / "src/backend/catalog/migrations/0001_initial.py").unlink()
    head = _commit(repository, "delete base migration")

    result = _check(repository, base, head)

    assert result.returncode == 1
    assert result.stdout == "src/backend/catalog/migrations/0001_initial.py\n"
    assert result.stderr == ""


def test_rejects_renamed_base_migration_as_a_deletion(tmp_path: Path) -> None:
    repository, base = _repository(tmp_path)
    _run(
        "git",
        "mv",
        "src/backend/catalog/migrations/0001_initial.py",
        "src/backend/catalog/migrations/0001_renamed.py",
        cwd=repository,
    )
    head = _commit(repository, "rename base migration")

    assert _run("git", "diff", "--name-status", base, head, cwd=repository).stdout == (
        "R100\tsrc/backend/catalog/migrations/0001_initial.py\t"
        "src/backend/catalog/migrations/0001_renamed.py\n"
    )

    result = _check(repository, base, head)

    assert result.returncode == 1
    assert result.stdout == "src/backend/catalog/migrations/0001_initial.py\n"
    assert result.stderr == ""


def test_allows_the_audited_optional_contact_migration_recovery(tmp_path: Path) -> None:
    repository, base = _selfie_search_recovery_repository(tmp_path)
    migrations = repository / "src/backend/selfie_search/migrations"
    (migrations / "0003_optional_feedback_contact.py").write_text(
        _HISTORICAL_OPTIONAL_CONTACT, encoding="utf-8"
    )
    (migrations / "0005_optional_feedback_contact.py").write_text(_RECOVERY_MERGE, encoding="utf-8")
    head = _commit(repository, "restore historical optional contact migration")

    result = _check(repository, base, head)

    assert result.returncode == 0
    assert result.stdout == ""
    assert result.stderr == ""


def test_rejects_optional_contact_recovery_when_historical_source_is_not_exact(
    tmp_path: Path,
) -> None:
    repository, base = _selfie_search_recovery_repository(tmp_path)
    migrations = repository / "src/backend/selfie_search/migrations"
    (migrations / "0003_optional_feedback_contact.py").write_text(
        "not historical\n", encoding="utf-8"
    )
    (migrations / "0005_optional_feedback_contact.py").write_text(_RECOVERY_MERGE, encoding="utf-8")
    head = _commit(repository, "corrupt historical migration")

    result = _check(repository, base, head)

    assert result.returncode == 1
    assert (
        result.stdout == "src/backend/selfie_search/migrations/0005_optional_feedback_contact.py\n"
    )
    assert result.stderr == ""


def test_rejects_optional_contact_recovery_when_merge_source_is_not_exact(tmp_path: Path) -> None:
    repository, base = _selfie_search_recovery_repository(tmp_path)
    migrations = repository / "src/backend/selfie_search/migrations"
    (migrations / "0003_optional_feedback_contact.py").write_text(
        _HISTORICAL_OPTIONAL_CONTACT, encoding="utf-8"
    )
    (migrations / "0005_optional_feedback_contact.py").write_text(
        f"{_RECOVERY_MERGE}# not an audited recovery\n", encoding="utf-8"
    )
    head = _commit(repository, "change recovery merge")

    result = _check(repository, base, head)

    assert result.returncode == 1
    assert (
        result.stdout == "src/backend/selfie_search/migrations/0005_optional_feedback_contact.py\n"
    )
    assert result.stderr == ""


def test_rejects_optional_contact_recovery_when_another_migration_changes(tmp_path: Path) -> None:
    repository, base = _selfie_search_recovery_repository(tmp_path)
    migrations = repository / "src/backend/selfie_search/migrations"
    (migrations / "0002_selfiesearchfeedback_and_more.py").write_text(
        "BASE = False\n", encoding="utf-8"
    )
    (migrations / "0003_optional_feedback_contact.py").write_text(
        _HISTORICAL_OPTIONAL_CONTACT, encoding="utf-8"
    )
    (migrations / "0005_optional_feedback_contact.py").write_text(_RECOVERY_MERGE, encoding="utf-8")
    head = _commit(repository, "change another migration")

    result = _check(repository, base, head)

    assert result.returncode == 1
    assert result.stdout == (
        "src/backend/selfie_search/migrations/0002_selfiesearchfeedback_and_more.py\n"
        "src/backend/selfie_search/migrations/0005_optional_feedback_contact.py\n"
    )
    assert result.stderr == ""
