global:
  resolve_timeout: 5m
route:
  receiver: unmatched
  group_by:
  - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
  - receiver: findme-email
    matchers:
    - project="findme-photo"
receivers:
- name: unmatched
  yandex_monitoring_configs:
  - channel_names: []
- name: findme-email
  yandex_monitoring_configs:
  - channel_names:
    - '{{channel_name}}'
    send_resolved: true
