# Generated by Django 6.0.6 on 2026-08-15 08:14

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picflow", "0008_photo_capture_time_projection"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="folders",
                        to="picflow.event",
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name"), "id"],
            },
        ),
        migrations.AddField(
            model_name="photo",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="photos",
                to="picflow.eventfolder",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventfolder",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(django.db.models.functions.text.Trim("name")),
                models.F("event"),
                name="picflow_folder_event_name_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventfolder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name", django.db.models.functions.text.Trim("name")),
                    models.Q(("name", ""), _negated=True),
                ),
                name="picflow_folder_name_trimmed_chk",
            ),
        ),
    ]
