# Generated by Django 6.0.6 on 2026-09-15 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picflow', '0015_bib_search_policy'),
        ('processing', '0010_face_projection_generation_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryMediaProjection',
            fields=[
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='gallery_media_projection', serialize=False, to='picflow.photo')),
                ('clean_preview_final_key', models.CharField(blank=True, max_length=255, null=True)),
                ('watermarked_preview_final_key', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clean_preview_source_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='processing.processingattempt')),
                ('watermarked_preview_source_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='processing.processingattempt')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('clean_preview_final_key__isnull', True), ('clean_preview_source_attempt__isnull', True)), models.Q(('clean_preview_final_key__isnull', False), ('clean_preview_source_attempt__isnull', False)), _connector='OR'), name='picflow_gallery_media_clean_pair_chk'), models.CheckConstraint(condition=models.Q(models.Q(('watermarked_preview_final_key__isnull', True), ('watermarked_preview_source_attempt__isnull', True)), models.Q(('watermarked_preview_final_key__isnull', False), ('watermarked_preview_source_attempt__isnull', False)), _connector='OR'), name='picflow_gallery_media_watermarked_pair_chk')],
            },
        ),
    ]
