# Generated by Django 6.0.6 on 2026-07-30 14:53

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import selfie_search.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("picflow", "0005_validate_photo_private_original_constraints"),
        ("processing", "0002_add_face_embedding_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelfieSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_token_digest", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("cleanup_pending", "Cleanup pending"),
                            ("ready", "Ready"),
                            ("no_face", "No face"),
                            ("multiple_faces", "Multiple faces"),
                            ("quality_rejected", "Quality rejected"),
                            ("search_unavailable", "Search unavailable"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("temporary_object_key", models.CharField(max_length=255)),
                ("temporary_object_etag", models.CharField(blank=True, default="", max_length=128)),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, validators=[selfie_search.models.validate_bounded_json]
                    ),
                ),
                ("configuration_hash", models.CharField(blank=True, default="", max_length=64)),
                ("eligible_photo_count", models.PositiveIntegerField(default=0)),
                ("eligible_face_count", models.PositiveIntegerField(default=0)),
                ("matched_photo_count", models.PositiveIntegerField(default=0)),
                ("failure_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "intended_terminal_status",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("state_changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                ("cleanup_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selfie_searches",
                        to="picflow.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelfieSearchCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "embedding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selfie_candidates",
                        to="processing.faceembedding",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selfie_candidates",
                        to="picflow.photo",
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="selfie_search.selfiesearch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelfieSearchJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("retry_wait", "Retry wait"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, validators=[selfie_search.models.validate_bounded_json]
                    ),
                ),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "search",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job",
                        to="selfie_search.selfiesearch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelfieSearchAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("stale", "Stale"),
                        ],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                ("result_hash", models.CharField(blank=True, default="", max_length=64)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_detail", models.CharField(blank=True, default="", max_length=512)),
                ("download_duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("compute_duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("total_duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("worker_started_at", models.DateTimeField(blank=True, null=True)),
                ("worker_finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="selfie_search.selfiesearchjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelfieSearchResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("cosine_distance", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selfie_results",
                        to="processing.photofacedetection",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selfie_results",
                        to="picflow.photo",
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="selfie_search.selfiesearch",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="selfiesearch",
            index=models.Index(fields=["event", "status"], name="selfie_search_event_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="selfiesearch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "queued",
                            "processing",
                            "cleanup_pending",
                            "ready",
                            "no_face",
                            "multiple_faces",
                            "quality_rejected",
                            "search_unavailable",
                            "failed",
                        ),
                    )
                ),
                name="selfie_search_status_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="selfiesearch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "intended_terminal_status__in",
                        (
                            "",
                            "ready",
                            "no_face",
                            "multiple_faces",
                            "quality_rejected",
                            "search_unavailable",
                            "failed",
                        ),
                    )
                ),
                name="selfie_search_intended_status_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="selfiesearchcandidate",
            constraint=models.UniqueConstraint(
                fields=("search", "embedding"), name="selfie_candidate_embedding_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="selfiesearchjob",
            index=models.Index(fields=["status", "available_at"], name="selfie_job_claim_idx"),
        ),
        migrations.AddConstraint(
            model_name="selfiesearchjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("queued", "processing", "retry_wait", "succeeded", "failed"))
                ),
                name="selfie_job_status_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="selfiesearchattempt",
            index=models.Index(fields=["job", "status"], name="selfie_attempt_job_status_idx"),
        ),
        migrations.AddIndex(
            model_name="selfiesearchattempt",
            index=models.Index(fields=["lease_expires_at"], name="selfie_attempt_lease_idx"),
        ),
        migrations.AddConstraint(
            model_name="selfiesearchattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("in_progress", "succeeded", "failed", "expired", "stale"))
                ),
                name="selfie_attempt_status_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="selfiesearchattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "in_progress"), ("terminal_at__isnull", True)),
                    models.Q(
                        ("status__in", ("succeeded", "failed", "expired", "stale")),
                        ("terminal_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="selfie_attempt_terminal_at_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="selfiesearchresult",
            index=models.Index(fields=["search", "rank"], name="selfie_result_search_rank_idx"),
        ),
        migrations.AddConstraint(
            model_name="selfiesearchresult",
            constraint=models.UniqueConstraint(
                fields=("search", "photo"), name="selfie_result_photo_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="selfiesearchresult",
            constraint=models.UniqueConstraint(
                fields=("search", "rank"), name="selfie_result_rank_uniq"
            ),
        ),
    ]
