# Generated by Django 6.0.6 on 2026-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selfie_search", "0004_remove_selfie_search_candidate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfiesearchfeedback",
            name="contact",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.RemoveConstraint(
            model_name="selfiesearchfeedback",
            name="selfie_feedback_contact_nonempty_chk",
        ),
    ]
