# Generated by Django 6.0.6 on 2026-08-21 09:17

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import commerce.models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0002_orders_and_payments"),
        ("picflow", "0013_event_photo_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommerceAttention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("payment_mismatch", "Payment mismatch"),
                            ("manual_payment_conflict", "Manual payment conflict"),
                            ("original_missing", "Original missing"),
                            ("email_exhausted", "Email exhausted"),
                            ("payment_reconciliation_overdue", "Payment reconciliation overdue"),
                            ("commerce_work_stale", "Commerce work stale"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("first_observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("next_reminder_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_source",
                    models.CharField(
                        blank=True,
                        choices=[("automatic", "Automatic"), ("admin", "Administrator")],
                        max_length=9,
                    ),
                ),
                ("resolution_comment", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="DownloadGrantAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "authorization_source",
                    models.CharField(
                        choices=[
                            ("purchase_browser", "Purchase browser"),
                            ("order_access_grant", "Order access grant"),
                        ],
                        max_length=18,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "message_kind",
                    models.CharField(choices=[("order_access", "Order access")], max_length=16),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("retry_wait", "Retry wait"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(db_index=True)),
                ("last_failure_category", models.CharField(blank=True, max_length=64)),
                ("lease_id", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("retryable_failure", "Retryable failure"),
                            ("terminal_failure", "Terminal failure"),
                        ],
                        max_length=18,
                    ),
                ),
                ("safe_failure_category", models.CharField(blank=True, max_length=64)),
                ("attempted_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("attempt_number",),
            },
        ),
        migrations.CreateModel(
            name="OrderAccessGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("checkout", "Checkout"),
                            ("resend", "Resend"),
                            ("admin", "Administrator"),
                        ],
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="first_customer_access_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="purchase_browser_token_sha256",
            field=models.CharField(
                default=commerce.models.generate_unclaimed_purchase_browser_digest,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Browser token digest must be 64 lowercase hexadecimal characters.",
                        regex="^[0-9a-f]{64}$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("purchase_browser_token_sha256__regex", "^[0-9a-f]{64}$")),
                name="commerce_order_purchase_digest_chk",
            ),
        ),
        migrations.AddField(
            model_name="commerceattention",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attention_records",
                to="commerce.order",
            ),
        ),
        migrations.AddField(
            model_name="commerceattention",
            name="payment_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attention_records",
                to="commerce.paymentattempt",
            ),
        ),
        migrations.AddField(
            model_name="downloadgrantaudit",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="download_grant_audits",
                to="commerce.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="email_deliveries",
                to="commerce.order",
            ),
        ),
        migrations.AddField(
            model_name="emaildeliveryattempt",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="commerce.emaildelivery",
            ),
        ),
        migrations.AddField(
            model_name="orderaccessgrant",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderaccessgrant",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access_grants",
                to="commerce.order",
            ),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="access_grant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="email_deliveries",
                to="commerce.orderaccessgrant",
            ),
        ),
        migrations.AddField(
            model_name="downloadgrantaudit",
            name="access_grant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="download_grant_audits",
                to="commerce.orderaccessgrant",
            ),
        ),
        migrations.AddIndex(
            model_name="commerceattention",
            index=models.Index(
                fields=["resolved_at", "next_reminder_at"],
                name="commerce_attention_open_reminder_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="commerceattention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        (
                            "payment_mismatch",
                            "manual_payment_conflict",
                            "original_missing",
                            "email_exhausted",
                            "payment_reconciliation_overdue",
                            "commerce_work_stale",
                        ),
                    )
                ),
                name="commerce_attention_kind_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="commerceattention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("resolution_comment", ""),
                        ("resolution_source", ""),
                        ("resolved_at__isnull", True),
                    ),
                    models.Q(
                        ("resolution_source__in", ("automatic", "admin")),
                        ("resolved_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="commerce_attention_resolution_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="commerceattention",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resolved_at__isnull", True)),
                fields=("kind", "subject"),
                name="commerce_attention_kind_subject_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildeliveryattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("outcome__in", ("succeeded", "retryable_failure", "terminal_failure"))
                ),
                name="commerce_email_attempt_outcome_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildeliveryattempt",
            constraint=models.UniqueConstraint(
                fields=("delivery", "attempt_number"), name="commerce_email_attempt_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="orderaccessgrant",
            index=models.Index(
                fields=["order", "revoked_at"], name="commerce_access_grant_order_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderaccessgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ("checkout", "resend", "admin"))),
                name="commerce_access_grant_source_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderaccessgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source", "admin"), _negated=True),
                    ("created_by__isnull", False),
                    _connector="OR",
                ),
                name="commerce_access_grant_admin_actor_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildelivery",
            index=models.Index(
                fields=["state", "next_attempt_at"], name="commerce_email_delivery_ready_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("message_kind", "order_access")),
                name="commerce_email_delivery_kind_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        ("pending", "processing", "retry_wait", "succeeded", "failed", "canceled"),
                    )
                ),
                name="commerce_email_delivery_state_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("lease_expires_at__isnull", False),
                        ("lease_id__isnull", False),
                        ("state", "processing"),
                    ),
                    models.Q(
                        models.Q(("state", "processing"), _negated=True),
                        ("lease_expires_at__isnull", True),
                        ("lease_id__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="commerce_email_delivery_lease_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="downloadgrantaudit",
            index=models.Index(
                fields=["order_item", "created_at"], name="commerce_download_audit_item_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="downloadgrantaudit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("access_grant__isnull", True), ("authorization_source", "purchase_browser")
                    ),
                    models.Q(
                        ("access_grant__isnull", False),
                        ("authorization_source", "order_access_grant"),
                    ),
                    _connector="OR",
                ),
                name="commerce_download_audit_source_chk",
            ),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION commerce_guard_order_fulfillment() RETURNS trigger AS $$
                BEGIN
                    IF OLD.purchase_browser_token_sha256 IS DISTINCT FROM
                            NEW.purchase_browser_token_sha256 THEN
                        RAISE EXCEPTION 'order purchase browser digest is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    IF OLD.first_customer_access_at IS NOT NULL
                       AND OLD.first_customer_access_at IS DISTINCT FROM
                            NEW.first_customer_access_at THEN
                        RAISE EXCEPTION 'order first customer access is set once'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER commerce_order_fulfillment_guard_trg
                    BEFORE UPDATE ON commerce_order
                    FOR EACH ROW
                    EXECUTE FUNCTION commerce_guard_order_fulfillment();

                CREATE FUNCTION commerce_guard_access_grant() RETURNS trigger AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION 'order access grants are durable and cannot be deleted'
                            USING ERRCODE = '23514';
                    END IF;
                    IF OLD.id IS DISTINCT FROM NEW.id
                       OR OLD.order_id IS DISTINCT FROM NEW.order_id
                       OR OLD.source IS DISTINCT FROM NEW.source
                       OR OLD.created_by_id IS DISTINCT FROM NEW.created_by_id
                       OR OLD.created_at IS DISTINCT FROM NEW.created_at
                       OR (
                            OLD.revoked_at IS NOT NULL
                            AND OLD.revoked_at IS DISTINCT FROM NEW.revoked_at
                       ) THEN
                        RAISE EXCEPTION 'order access grant metadata is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER commerce_access_grant_guard_trg
                    BEFORE UPDATE OR DELETE ON commerce_orderaccessgrant
                    FOR EACH ROW
                    EXECUTE FUNCTION commerce_guard_access_grant();

                CREATE FUNCTION commerce_guard_email_delivery() RETURNS trigger AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION 'email deliveries are durable and cannot be deleted'
                            USING ERRCODE = '23514';
                    END IF;
                    IF OLD.order_id IS DISTINCT FROM NEW.order_id
                       OR OLD.message_kind IS DISTINCT FROM NEW.message_kind
                       OR OLD.recipient_email IS DISTINCT FROM NEW.recipient_email
                       OR OLD.access_grant_id IS DISTINCT FROM NEW.access_grant_id
                       OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
                        RAISE EXCEPTION 'email delivery recipient snapshot is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER commerce_email_delivery_guard_trg
                    BEFORE UPDATE OR DELETE ON commerce_emaildelivery
                    FOR EACH ROW
                    EXECUTE FUNCTION commerce_guard_email_delivery();

                CREATE FUNCTION commerce_validate_email_delivery_grant() RETURNS trigger AS $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM commerce_orderaccessgrant
                        WHERE id = NEW.access_grant_id
                          AND order_id = NEW.order_id
                    ) THEN
                        RAISE EXCEPTION 'email delivery grant must belong to its order'
                            USING ERRCODE = '23514';
                    END IF;
                    IF TG_OP = 'INSERT'
                       AND NOT EXISTS (
                            SELECT 1
                            FROM commerce_order
                            WHERE id = NEW.order_id
                              AND delivery_email = NEW.recipient_email
                       ) THEN
                        RAISE EXCEPTION 'email delivery recipient must match its order'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER commerce_email_delivery_grant_guard_trg
                    BEFORE INSERT OR UPDATE ON commerce_emaildelivery
                    FOR EACH ROW
                    EXECUTE FUNCTION commerce_validate_email_delivery_grant();

                CREATE FUNCTION commerce_guard_email_attempt() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'email delivery attempts are append-only'
                        USING ERRCODE = '23514';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER commerce_email_attempt_guard_trg
                    BEFORE UPDATE OR DELETE ON commerce_emaildeliveryattempt
                    FOR EACH ROW
                    EXECUTE FUNCTION commerce_guard_email_attempt();

                CREATE FUNCTION commerce_validate_email_attempt_recipient() RETURNS trigger AS $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM commerce_emaildelivery
                        WHERE id = NEW.delivery_id
                          AND recipient_email = NEW.recipient_email
                    ) THEN
                        RAISE EXCEPTION 'email attempt recipient must match its delivery'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER commerce_email_attempt_recipient_guard_trg
                    BEFORE INSERT ON commerce_emaildeliveryattempt
                    FOR EACH ROW
                    EXECUTE FUNCTION commerce_validate_email_attempt_recipient();

                CREATE FUNCTION commerce_guard_attention() RETURNS trigger AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION 'commerce attention is durable and cannot be deleted'
                            USING ERRCODE = '23514';
                    END IF;
                    IF OLD.kind IS DISTINCT FROM NEW.kind
                       OR OLD.subject IS DISTINCT FROM NEW.subject
                       OR OLD.order_id IS DISTINCT FROM NEW.order_id
                       OR OLD.payment_attempt_id IS DISTINCT FROM NEW.payment_attempt_id
                       OR OLD.first_observed_at IS DISTINCT FROM NEW.first_observed_at THEN
                        RAISE EXCEPTION 'commerce attention identity is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    IF OLD.resolved_at IS NOT NULL
                       AND (
                            OLD.resolved_at IS DISTINCT FROM NEW.resolved_at
                            OR OLD.resolution_source IS DISTINCT FROM NEW.resolution_source
                            OR OLD.resolution_comment IS DISTINCT FROM NEW.resolution_comment
                       ) THEN
                        RAISE EXCEPTION 'commerce attention resolution is write-once'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER commerce_attention_guard_trg
                    BEFORE UPDATE OR DELETE ON commerce_commerceattention
                    FOR EACH ROW
                    EXECUTE FUNCTION commerce_guard_attention();

                CREATE FUNCTION commerce_guard_download_audit() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'download grant audits are append-only'
                        USING ERRCODE = '23514';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER commerce_download_audit_guard_trg
                    BEFORE UPDATE OR DELETE ON commerce_downloadgrantaudit
                    FOR EACH ROW
                    EXECUTE FUNCTION commerce_guard_download_audit();

                CREATE FUNCTION commerce_validate_download_audit_grant() RETURNS trigger AS $$
                BEGIN
                    IF NEW.authorization_source = 'order_access_grant'
                       AND NOT EXISTS (
                            SELECT 1
                            FROM commerce_orderaccessgrant grant_record
                            JOIN commerce_orderitem item
                              ON item.id = NEW.order_item_id
                            WHERE grant_record.id = NEW.access_grant_id
                              AND grant_record.order_id = item.order_id
                       ) THEN
                        RAISE EXCEPTION 'download audit grant must belong to the item order'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER commerce_download_audit_grant_guard_trg
                    BEFORE INSERT ON commerce_downloadgrantaudit
                    FOR EACH ROW
                    EXECUTE FUNCTION commerce_validate_download_audit_grant();
            """,
            reverse_sql="""
                DROP TRIGGER commerce_download_audit_grant_guard_trg
                    ON commerce_downloadgrantaudit;
                DROP FUNCTION commerce_validate_download_audit_grant();
                DROP TRIGGER commerce_download_audit_guard_trg
                    ON commerce_downloadgrantaudit;
                DROP FUNCTION commerce_guard_download_audit();
                DROP TRIGGER commerce_attention_guard_trg
                    ON commerce_commerceattention;
                DROP FUNCTION commerce_guard_attention();
                DROP TRIGGER commerce_email_attempt_guard_trg
                    ON commerce_emaildeliveryattempt;
                DROP FUNCTION commerce_guard_email_attempt();
                DROP TRIGGER commerce_email_attempt_recipient_guard_trg
                    ON commerce_emaildeliveryattempt;
                DROP FUNCTION commerce_validate_email_attempt_recipient();
                DROP TRIGGER commerce_email_delivery_guard_trg
                    ON commerce_emaildelivery;
                DROP FUNCTION commerce_guard_email_delivery();
                DROP TRIGGER commerce_email_delivery_grant_guard_trg
                    ON commerce_emaildelivery;
                DROP FUNCTION commerce_validate_email_delivery_grant();
                DROP TRIGGER commerce_access_grant_guard_trg
                    ON commerce_orderaccessgrant;
                DROP FUNCTION commerce_guard_access_grant();
                DROP TRIGGER commerce_order_fulfillment_guard_trg ON commerce_order;
                DROP FUNCTION commerce_guard_order_fulfillment();
            """,
        ),
    ]
