# Generated by Django 6.0.6 on 2026-07-13 19:08

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("picflow", "0005_validate_photo_private_original_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "expected_item_count",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("uploading", "Uploading"),
                            ("completed", "Completed"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_batches",
                        to="picflow.event",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [("upload_photos", "Can upload photos")],
            },
        ),
        migrations.CreateModel(
            name="UploadItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("client_item_id", models.UUIDField()),
                ("original_filename", models.CharField(max_length=255)),
                ("declared_content_type", models.CharField(max_length=100)),
                (
                    "expected_size",
                    models.BigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52428800),
                        ]
                    ),
                ),
                ("incoming_key", models.CharField(max_length=255, unique=True)),
                ("final_key", models.CharField(max_length=255, unique=True)),
                ("verified_source_etag", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("uploaded", "Uploaded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "sanitized_error_message",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("authorization_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("upload_attempts", models.PositiveSmallIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ingestion.uploadbatch",
                    ),
                ),
                (
                    "photo",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_item",
                        to="picflow.photo",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="uploadbatch",
            index=models.Index(
                fields=["uploader", "-created_at"], name="ing_batch_uploader_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadbatch",
            index=models.Index(
                fields=["status", "last_activity_at"], name="ing_batch_status_activity_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_item_count__gte", 1), ("expected_item_count__lte", 10000)
                ),
                name="ing_batch_expected_count_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("created", "uploading", "completed", "partial", "failed"))
                ),
                name="ing_batch_status_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="uploaditem",
            index=models.Index(fields=["batch", "status"], name="ing_item_batch_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="uploaditem",
            constraint=models.UniqueConstraint(
                fields=("batch", "client_item_id"), name="ing_item_batch_client_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="uploaditem",
            constraint=models.CheckConstraint(
                condition=models.Q(("declared_content_type", "image/jpeg")),
                name="ing_item_jpeg_content_type_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="uploaditem",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_size__gte", 1), ("expected_size__lte", 52428800)),
                name="ing_item_expected_size_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="uploaditem",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("pending", "authorized", "uploaded", "failed"))),
                name="ing_item_status_chk",
            ),
        ),
    ]
