# Generated by Django 6.0.6 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploaditem",
            name="ambiguous_sha256",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="uploaditem",
            name="client_last_modified_ms",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
