# Generated by Django 6.0.6 on 2026-08-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0002_upload_item_resume_metadata"),
        ("picflow", "0009_eventfolder_photo_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploaditem",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="upload_items",
                to="picflow.eventfolder",
            ),
        ),
    ]
