# Generated by Django 6.0.6 on 2026-09-07
# ruff: noqa: E501

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0003_uploaditem_folder"),
        ("picflow", "0013_event_photo_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("submitted_source_key", models.CharField(max_length=512)),
                ("submission_key", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("enumerating", "Enumerating"),
                            ("transferring", "Transferring"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("partial", "Completed with errors"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("manifest_complete", models.BooleanField(default=False)),
                ("manifest_attempts", models.PositiveSmallIntegerField(default=0)),
                ("jpeg_count", models.PositiveIntegerField(default=0)),
                ("directory_count", models.PositiveIntegerField(default=0)),
                ("unsupported_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photo_import_batches",
                        to="picflow.event",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photo_import_batches",
                        to="picflow.eventfolder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photo_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_path", models.CharField(max_length=1024)),
                ("filename", models.CharField(max_length=255)),
                (
                    "byte_size",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("source_sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("source_md5", models.CharField(blank=True, max_length=32, null=True)),
                ("source_version", models.CharField(blank=True, default="", max_length=255)),
                ("content_sha256", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("uploading", "Uploading"),
                            ("imported", "Imported"),
                            ("duplicate", "Already imported"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("download_attempts", models.PositiveSmallIntegerField(default=0)),
                ("upload_attempts", models.PositiveSmallIntegerField(default=0)),
                ("retry_generation", models.PositiveSmallIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ingestion.importbatch",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_items",
                        to="picflow.photo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("manifest", "Manifest"), ("file", "File")], max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("claimed_at", models.DateTimeField()),
                ("heartbeat_at", models.DateTimeField()),
                ("lease_expires_at", models.DateTimeField()),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("content_sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("byte_size", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "incoming_key",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("final_key", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("verified_source_etag", models.CharField(blank=True, default="", max_length=128)),
                ("verified_final_etag", models.CharField(blank=True, default="", max_length=128)),
                ("oriented_width", models.PositiveIntegerField(blank=True, null=True)),
                ("oriented_height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="ingestion.importbatch",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="ingestion.importitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportManifestPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("entry_count", models.PositiveIntegerField()),
                ("jpeg_count", models.PositiveIntegerField(default=0)),
                ("directory_count", models.PositiveIntegerField(default=0)),
                ("unsupported_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manifest_pages",
                        to="ingestion.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("canonical_source_key", models.CharField(max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photo_import_scopes",
                        to="picflow.event",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photo_import_scopes",
                        to="picflow.eventfolder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photo_import_scopes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sha256", models.CharField(max_length=64)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "photo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imported_content",
                        to="picflow.photo",
                    ),
                ),
                (
                    "source_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_content",
                        to="ingestion.importitem",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contents",
                        to="ingestion.importscope",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="importbatch",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="ingestion.importscope",
            ),
        ),
        migrations.AddIndex(
            model_name="importitem",
            index=models.Index(fields=["batch", "status"], name="ing_import_item_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="importitem",
            constraint=models.UniqueConstraint(
                fields=("batch", "source_path"), name="ing_import_item_path_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="importitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("byte_size__gte", 1)),
                name="ing_import_item_size_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="importitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("download_attempts__lte", 4), ("upload_attempts__lte", 4)),
                name="ing_import_item_attempts_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="importattempt",
            index=models.Index(
                fields=["status", "lease_expires_at"], name="ing_import_attempt_lease_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="importattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("item__isnull", True), ("kind", "manifest")),
                    models.Q(("item__isnull", False), ("kind", "file")),
                    _connector="OR",
                ),
                name="ing_import_attempt_item_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="importmanifestpage",
            constraint=models.UniqueConstraint(
                fields=("batch", "page_number"), name="ing_import_manifest_page_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="importscope",
            constraint=models.UniqueConstraint(
                fields=("owner", "canonical_source_key", "event", "folder"),
                name="ing_import_scope_uniq",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="importedcontent",
            constraint=models.UniqueConstraint(
                fields=("scope", "sha256", "byte_size"), name="ing_import_content_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["status", "created_at"], name="ing_import_batch_claim_idx"),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["owner", "-created_at"], name="ing_import_owner_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                fields=("owner", "submission_key"), name="ing_import_owner_submission_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("manifest_attempts__gte", 0), ("manifest_attempts__lte", 4)),
                name="ing_import_manifest_attempts_chk",
            ),
        ),
    ]
